development:
  domain: localhost:3000
  storage: filesystem

test:
  domain: test.host
  storage: filesystem
  hoptoad: false
  
production:
  domain: xn--backenhrnchen-omb.de
  storage: amazon_s3
  hoptoad: true
  bucket: ozzi
  host_alias: media.xn--backenhrnchen-omb.de
