development:
  domain: localhost:3000
  storage: filesystem
  hoptoad: false
  bucket: ozzi-development
  host_alias: d2ohw747sglmss.cloudfront.net  

test:
  domain: test.host
  storage: filesystem  
  hoptoad: false
  
production:
  domain: backenhörnchen.de
  storage: amazon_s3
  hoptoad: true
  bucket: ozzi
  host_alias: media.backenhörnchen.de
