development:
  domain: localhost:3000
  storage: filesystem

test:
  domain: test.host
  storage: filesystem
  hoptoad: false
  
production:
  domain: australia.heroku.com
  storage: amazon_s3
  hoptoad: true
  bucket: ozzi2
  # host_alias: media.xn--backenhrnchen-omb.de
